server:
  port: 9999
 
spring:
  application:
    name: API-SERVICE

  cloud:
    gateway:
      routes:
      - id: AUTH-SERVICE
        uri: lb://AUTH-SERVICE
        predicates:
        - Path=/auth/**
                    
      - id: STUDENT-SERVICE
        uri: lb://STUDENT-SERVICE
        predicates:
        - Path=/student/**
        
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/    